### ISSUE TITLE
Missing anchors, Wrong types

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#101]
`uni08E6` (kasraCurly-ar) is not a mark but should be one. Maybe it misses just a `_bottom` anchor and is subsequently not exported as a mark. It's a mark by default.

![selection_071](https://cloud.githubusercontent.com/assets/393132/12992423/abb04de8-d114-11e5-9302-fa3de9cc7a69.png)

`circumflex.below`, same as above:

![selection_072](https://cloud.githubusercontent.com/assets/393132/12992520/390b6a6a-d115-11e5-838a-7b2465af3d91.png)

**Comment by Tarobish** [comment]
missing anchors, repo has been updated

**Comment by graphicore** [comment]
`circumflex.below` is still broken, probably you have to make it a mark explicitly yourself.

**Comment by Tarobish** [comment]
Please check it out :D

**Comment by graphicore** [comment]
Something is still wrong there.

**Comment by Tarobish** [comment]
How about now?

**Comment by graphicore** [comment]
[Here is an example](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%233%3A%20Ligature%2003%20%28uni066E0631%29) in the line of `uni0755.init`

![selection_074](https://cloud.githubusercontent.com/assets/393132/13037353/2d54e126-d37f-11e5-8bcc-059854617503.png)

I just discovered that this looks also bad in [Katibeh](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%233%3A%20Ligature%2003%20%28uni066E0631%29)!

However, `vbelowar` is very similar, and that one works, in the line of `uni08A0.init`

Maybe you can compare these and find out what the difference is?

**Comment by Tarobish** [comment]
I made some changes please check it out

**Comment by graphicore** [comment]
Nothing. What did you change?

**Comment by Tarobish** [comment]
Delete and Added new anchors, please check it one more time

**Comment by graphicore** [comment]
:+1: That's it!

![selection_076](https://cloud.githubusercontent.com/assets/393132/13058404/5b2b0298-d423-11e5-9bb3-607fc86a9164.png)

I'll update the fonts in a second.

**Comment by Tarobish** [comment]
Awesome :)
