### ISSUE TITLE
Make a descriptive text for the font

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#102]
For the same use cases as [this in Jomhuria](https://github.com/Tarobish/Jomhuria#jomhuria-font-project).

@Tarobish: I can help you to get it into shape, but you should deliver a starting point.

**Comment by Tarobish** [comment]
Mirza its a body text based on Naskh script, in 4 different sizes. we tried to observe the rules of the Arabic and Persian aesthetics with the help of ligatures. with this quality, Arabic and Persian readers, they are familiar with the shapes of the character to make them comfortable for reading text. unlike the other Arabic fonts, Mirza has a Latin version which is design to have harmony for multilingual scripts.
