### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Mirza#103]
- [x] @davelab6 to do a QA check
- [x] Put description in #102 in README.md 
- [x] README needs other info similar to https://github.com/Tarobish/Jomhuria/blob/gh-pages/README.md
- [x] set the gh-pages branch to default and remove the master branch
- [x] add description and URL to the top of the project page
- [x] regenerate ttfs without an intermediate OTF step to reduce filesize
- [x] ~~perhaps remove some glyphs that are not used directly now, because of the decompositions~~

**Comment by graphicore** [comment]
For the TTFs we are now from ~ 323 kB  to ~ 177 kB

```
 Build/Mirza-Bold.otf     | Bin 166448 -> 166200 bytes
 Build/Mirza-Bold.ttf     | Bin 323080 -> 176372 bytes
 Build/Mirza-Medium.otf   | Bin 171836 -> 177880 bytes
 Build/Mirza-Medium.ttf   | Bin 328548 -> 176628 bytes
 Build/Mirza-Regular.otf  | Bin 165228 -> 165124 bytes
 Build/Mirza-Regular.ttf  | Bin 329072 -> 177064 bytes
 Build/Mirza-SemiBold.otf | Bin 172340 -> 177828 bytes
 Build/Mirza-SemiBold.ttf | Bin 327336 -> 176456 bytes
```

**Comment by davelab6** [comment]
NICE

**Comment by davelab6** [comment]
fsType must be 0, is currently 8

**Comment by davelab6** [comment]
The name table is set up wrong, please make them per https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0
- [x] Bold should be style name and not in family name; in Glyphs check the 'style link is bold' box here,

<img width="582" alt="screen shot 2016-02-26 at 13 11 31" src="https://cloud.githubusercontent.com/assets/261579/13361056/784fcbaa-dc8a-11e5-8cec-3cfb28d1be7f.png">
- [x] Bold needs fsSelection bold bit set
- [x] nameID 4 Full name `<namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">` should have spaces no dashes, eg `Mirza Bold` not `Mirza-Bold`
- [x] name ID 4 Full Name for Regular should not have `Regular` but just be family name
- [x] nameIDs 16 and 17 not needed in Bold or Regular
- [x] vendorID is `GRCR`, what is that mean? Ideally use one registered with MS at https://www.microsoft.com/typography/links/vendorlist.aspx

**Comment by graphicore** [comment]
> vendorID is `GRCR`, what is that mean? Ideally use one registered with MS at 

In https://github.com/Tarobish/Jomhuria/issues/39#issue-108435160 you said:

> OS/2 table <achVendID value=" "/> should be <achVendID value="GRCR"/> for Graphicore, or whatever. 

This is what I did here as well. I'm now writing the registration mail.

**Comment by davelab6** [comment]
Awesome!

**Comment by davelab6** [comment]
PRs welcome on https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md

**Comment by graphicore** [comment]
@Tarobish can you please take care of this 

> Bold should be style name and not in family name; in Glyphs check the 'style link is bold' box here

There's a screenshot attached. https://github.com/Tarobish/Mirza/issues/103#issuecomment-189408148

I think can take care of the rest then, but this first one is well handled in the source.

**Comment by Tarobish** [comment]
Please check it

**Comment by graphicore** [comment]
Yeah thanks, I think that'll do. I'll continue tomorrow.

**Comment by graphicore** [comment]
Uh @Tarobish can you do the same thing somehow for the other weights. Just if possible. Seems like it improves a lot of the issues above. Well, I'm not sure though if checking `is Bold` is correct for medium and semi-bold.

Maybe "Medium" is Bold of Regular
and "SemiBold" is Bold of Medium
and "Bold" is Bold of SemiBold

I have no idea.

**Comment by davelab6** [comment]
No don't do that. Only Bold should be style linked to Regular.

**Comment by graphicore** [comment]
I'm registered https://www.microsoft.com/typography/links/vendor.aspx?VID=GRCR

**Comment by graphicore** [comment]
Ok, that's all so far.

I'm now going to massage the project directory structures of Jomhuria/Mirza/Katibeh a bit to make match 

> PRs welcome on https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md

a bit better.

**Comment by davelab6** [comment]
Great!

On 2 March 2016 at 13:33, Lasse Fister notifications@github.com wrote:

> Ok, that's all so far.
> 
> I'm now going to massage the project directory structures of
> Jomhuria/Mirza/Katibeh a bit to make match
> 
> PRs welcome on
> https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md
> 
> a bit better.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tarobish/Mirza/issues/103#issuecomment-191362512.

## 

Cheers
Dave

**Comment by graphicore** [comment]
The directory structures of all three projects now look like this:

```
Mirza$ ls
AUTHORS.txt       Fonts       Makefile   Sources
CONTRIBUTORS.txt  html        OFL.txt    Tools
Documents         index.html  README.md  VERSION.txt
```

**Comment by graphicore** [comment]
There's one thing left on the current list:

> perhaps remove some glyphs that are not used directly now, because of the decompositions 

Which I think will not do so much, because the glyphs in question are all composite glyphs. You want me to try it anyways?

**Comment by davelab6** [comment]
No no, that's fine for me.
