### ISSUE TITLE
ligature 58 (uniFCCA)

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#58]
It has to be default for Arabic and style for the other scripts

uni06B6.init
uni06B5.init
uniFEDF
uni08A6.init
uni06B8.init
uni06B7.init
uni076A.init
+
uniFB81
uniFB7D
uniFEA0
uniFEA4
uniFB75
uniFB79
uni0757.medi
uni0682.medi
uni0681.medi
uniFEA8
uni0758.medi
uni0685.medi
uni077C.medi
uni076F.medi
uni076E.medi
uni08A2.medi
uni0772.medi

**Comment by graphicore** [comment]
Documenting progress:

Notes of #59 apply here too (almost, but the issue is similar)

White Mirza, Yellow Amir

![screen shot 2015-12-16 at 22 32 26](https://cloud.githubusercontent.com/assets/393132/11854592/1727e8d0-a445-11e5-8827-f4749feb5d60.png)
