### ISSUE TITLE
Colliding glyph combinations 01

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#60]
Final Alef with Mark below the baseline (the Connection it has to be very small, please add a new Keshida like "uni0640" as a connection part; later, i'll adjust the length :) )

uniFB5C
uniFB58
uni0754.init
uni0753.init
uni0752.init
uniFEF3
uni08A9.init
uni06CE.init
uni063E.init
uniFBFE
uni063D.init
uni0776.init
uni0775.init
uni063F.init
uni0767.init
+
uniFE8E.short
uniFE8E
uniFB51
uniFE82
uni0673.fina
uni0672.fina
uniFE88
uniFE84
uniFD3C
uni0774.fina
uni0773.fina

**Comment by graphicore** [comment]
By the way, the glyph used as extender is called `extender`. When you add it to the fonts, tell me, then I remove my version.
