### ISSUE TITLE
Especial character 01

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#66]
There are a few characters which they don't have a Unicode value, that would be great if we add them as a style (they are really common specialy for Persian)
(with extra part above as a "gaf") the style has to change normal "gaf" to these characters)
uni06AA.medi to uniFB95.001
uni06AA.init to uniFB94.001
uni06AA.fina to uniFB93.001
uni06AA to uni06AF.001

**Comment by Tarobish** [comment]
Just added the characters and tagged them with the green color

**Comment by graphicore** [comment]
also #67 

[live testing link](http://tarobish.github.io/Mirza/html/live-testing.html#?eJyVUcFOwzAM/RUrk9iFjCyUTEvHpAn+AE4ol4y5U6USqsYVA8q/47QUAQIBOcTvWbafn/wsivtAwoqHTClxLAgPdFk2nGioYo53V+UTMl3omphXPuyZ+YbxLXdi31zG2CJMjHHBhQ52WPi2IugAYlRz6Dgp+2ffIoNUuIq1D+ujyUGZzSb/GmEEq5OhLmxjnX/8oesnQKTHCs+nyYos0FPboIxIVIZ9tE6kJZyYruGvSmljF0ZXi0+uvtviF5+DzUHkQudjfBeDf7n4YQwL8U12ntK1tJobqbRUZ9dK2+zU6uUs0+ZGvLwCqJyVEg==)

![screen shot 2016-02-05 at 04 46 24](https://cloud.githubusercontent.com/assets/393132/12837477/7b652bd2-cbc3-11e5-9c38-440315a91586.png)

**Comment by Tarobish** [comment]
They just looks perfect :)

**Comment by graphicore** [comment]
You made them ;-)

**Comment by Tarobish** [comment]
You are the only one who can do this :)

**Comment by graphicore** [comment]
Hehe, thanks! But this was an easy one :-)

**Comment by Tarobish** [comment]
uni06AF
uniFB93
uniFB95
uniFB94

**Comment by Tarobish** [comment]
uniFEEA to uniFBA7

**Comment by Tarobish** [comment]
uni06AF to uni06AF.001
uniFB93 to uniFB93.001
uniFB95 to uniFB95.001
uniFB94 to uniFB94.001
uniFEEA to uniFBA7
uniFB90 to uni06AA.init
uniFB91 to uni06AA.medi
uniFB8F to uni06AA.fina
uni06A9 to uni06AA
