### ISSUE TITLE
OTF Error

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#76]
After Updating the features, we have this error 
it seems it has something to do with the line 35 and 36 (i guess :) )

![screen shot 2015-12-05 at 10 43 37 pm](https://cloud.githubusercontent.com/assets/8403973/11612133/6fef03d2-9ba2-11e5-9b61-a8012bdf393a.png)
![screen shot 2015-12-05 at 10 48 59 pm](https://cloud.githubusercontent.com/assets/8403973/11612134/72f3106e-9ba2-11e5-92e2-5218cbfe2141.png)

**Comment by graphicore** [comment]
This is how we solved it: https://forum.glyphsapp.com/t/bug-with-ccmp-feature-creation-for-arabic-fonts/3531/2

money quotes:

Georg: 

> Then you have a two glyphs that are made from hamzaabove fathatan. You need to remove one of them.

Me:

> turning it [GlyphsApp] off and on again worked, after removing the duplicate.
