### ISSUE TITLE
Wrongly Constructed Glyphs

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#79]
I'm just detecting some wrongly constructed Glyphs. Stuff like the marks are above, but they should be below. And also the usage of the wrong marks in these cases.

The isolated forms should get fixed!
While I don't need the uniXXX.{ini|medi|fina} forms of these glyphs (probably we can get rid of them in the end)

I will need however the mark-characters that go into the right place. So, it is not enough to just move the "above"-marks around, I also need proper "below"-marks …

I won't make an issue for each glyph, instead I'm documenting what I find within this issue.

**Comment by graphicore** [comment]
uni076E is constructed with: `uni062D uni0615`
but should be `uni062D uniFBC1`

uni076F is constructed with: `uni062D uniFBB4 uni0615`
but should be `uni062D uniFBB5 uniFBC1`

![selection_087](https://cloud.githubusercontent.com/assets/393132/11847428/a093b7c0-a41d-11e5-8c03-199687e7cd63.png)

**Comment by graphicore** [comment]
uni077C is made as a merged contour. We will create its [init|medi|fina] forms using the **missing `uni0664.below`** (ARABIC-INDIC DIGIT FOUR BELOW)

Could then also be constructed as: uni062D uni0664.below

**Comment by graphicore** [comment]
This uses `dotcenterar` as in the construction of uni08A2. The mark goes to the wrong place though.

![selection_089](https://cloud.githubusercontent.com/assets/393132/11848212/8905ea66-a421-11e5-9f76-928e59f8c110.png)

Note: not even Amiri can do this.

**Comment by Tarobish** [comment]
uni077C is made as a merged contour. We will create its [init|medi|fina] forms using the missing uni0664.below (ARABIC-INDIC DIGIT FOUR BELOW)

Could then also be constructed as: uni062D uni0664.below

| It Has been fixed

**Comment by Tarobish** [comment]
uni076E is constructed with: uni062D uni0615
but should be uni062D uniFBC1

uni076F is constructed with: uni062D uniFBB4 uni0615
but should be uni062D uniFBB5 uniFBC1

selection_087

| It Has been fixed

**Comment by Tarobish** [comment]
I didn't closed this issue to be sure abut all the constricted glyphs

**Comment by graphicore** [comment]
yeah don't close, there's still much to do for me :-)
