### ISSUE TITLE
 uniFC40 anchor above positioning seems odd

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#81]
![selection_086](https://cloud.githubusercontent.com/assets/393132/11847167/6945762e-a41c-11e5-9f43-692a25d0a974.png)

Top Mirza, bottom Amiri

While the v is positioned the same, the other marks are on the left instead on the right.

**Comment by Tarobish** [comment]
No its fine, Actually Khaled decided to have in that position, probably because of the space.
the characters we have here, its combination of لـ + خ normally dots goes where i placed them. but its up to us to decide which position works better

**Comment by graphicore** [comment]
:+1:
