### ISSUE TITLE
Check after deconstruction all unligated, deconstructed Glyphs.

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#82]
There are going to be missing marks and marks that go to wrong places. I'll make a testing table with all the deconstructed glyphs: isol, init, medi, fina forms.

@Tarobish  then you will likely have to fix some anchor positions and so on. Essentially the stuff that I'm describing in the issues before this one (#79 etc.) for the ligatures

But that table will help a lot. We are changing a lot of the logic that glyphs made for us, I hope it won't be too catastrophic. There's no other way to substitute the missing ligatures that you requested though.

We'll, you could also draw the missing ligatures.

Thinking of this, it will also have effects on the kerning! you wont need to do so much kerning in the end. However, you can't know what do do no, I think :-/

**Comment by Tarobish** [comment]
That would be great, with the table i can fix them really soon :) No worries :)

**Comment by graphicore** [comment]
Yeah, I think it wont be much to fix, once all decompositions that are needed have been made.

**Comment by graphicore** [comment]
I did not make that table yet. However, I made all tables for the issues for ligatures and collisions. The Ligatures work for the most parts, but some cases are failing, in each combination. I think we need a way to identify them and find a way to fix them.

Most problems are characters that we want to use as "mark", but that have a wrong type i.e. "base glyph" And I bet many of the problems that we had/have with adding new marks is because of this problem. "Mark to Mark" and "Mark to Base" positioning will fail if these Glyphs are not of type mark.

Unfortunately I think it's not straight forward to set the type of a glyph in GlyphsApp. But maybe, with the `GlyphData.xml` file we can make a `genericMark` glyph and re-use that.

That new entry would look like this:

``` xml
<glyph name="generic-mark-ar" sortName="ar9999" category="Mark" subCategory="Nonspacing" script="arabic" description="ARABIC GENERIC MARK TO DERIVE NEW MARKS"/>
```

Mirza with the fonts updated by me: http://tarobish.github.io/Mirza/html/generated-pages.html
Katibeh with the font updated by me: http://tarobish.github.io/Katibeh/html/generated-pages.htm

I'll post screenshot's of the tables over the next few days and describe what's going wrong in each case.

**Comment by graphicore** [comment]
@Tarobish I started commenting on #1, #2, #3. It looks like we need to find out how you can make real "marks" out of your marks. This will solve a ton of problems that we have now.

**Comment by graphicore** [comment]
@Tarobish Note that all test cases are done and most ligatures appear just fine (i.e. the issues are fixed). You can check them yourself and see what's going on. The errors that we see are rather other issues that spread through all ligatures where the affected glyphs are used.

However, we can well leave these issues open and close them when everything works.

Also, I applied the same features to Katibeh, and it seems to work just fine so far.

**Comment by Tarobish** [comment]
Exactly, they just works perfect. we just need to find a way to fix the decompositions problem

**Comment by graphicore** [comment]
I updated the gh-pages branch. Looks much better since we made all the mark characters really of type "mark". I'll care for the collisions and the other issues next.

**Comment by Tarobish** [comment]
Great! :)
