### ISSUE TITLE
Ignore Kerning if ...

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#85]
Ignore kerning if "uni0627" and "uni0627.short" has marks below the baseline
+
uni066E0649
uni066E06BA
uni066E0631
uni066E0631.fina
uni06A10649

---

Ignore "AlefFina" if it has marks below the baseline
+
"dotlessbeh_alefMaksura-ar" if Alef has a mark's below
"dotlessbeh_noonghunna-ar" if Alef has a mark's below
"dotlessbeh_reh-ar" if Alef has a mark's below
"dotlessfeh_alefMaksura-ar" if Alef has a mark's below
"lam_alefMaksura-ar" if Alef has a mark's below
"lam_meem-ar" if Alef has a mark's below
"lam_meem-ar.init" if Alef has a mark's below
"lam_meem_alefMaksura-ar" if Alef has a mark's below
"meem_meem-ar.init" if Alef has a mark's below

ـــــــــــــــــــــــــ
uniFD0E
uniFD2A
uni066E0631
uni066E0631.fina
uniFD0F
uniFD2B
uniFEAE
uni0631
uni0694.fina
uni0694
uni0693.fina
uni0693
uni0692.fina
uni0692
uniFB8D
uni0691
uniFEB0
uni0632
uni06EF.fina
uni06EF
uni0699.fina
uni0699
uniFB8B
uni0698
uni0697.fina
uni0697
uni0696.fina
uni0696
uni0695.fina
uniFC5C
uni0771.fina
uni0771
uni076C.fina
uni076C
uni076B.fina
uni076B
uni075B.fina
uni075B
uni06CA.fina
uni06CA
uni06C4.fina
uni06C4
uniFEEE
uni0648
uni06C5
uni08AB.fina
uni08AB
uni0779.fina
uni0779
uni0778.fina
uni0778
uniFE86
uni0624
uni06CF.fina
uni06CF
uniFBDF
uni06CB
uniFBE3
uni06C9
uniFBDC
uni06C8
uniFBD8
uni06C7
uniFBDA
uni06C6
uniFBE1
uni0677.fina
uni0677
uni0676
uni0676
+
"uni0627" and "uni0627.short" if AlefIso has mark's below

**Comment by graphicore** [comment]
In the first block, I won't include `uni066E0631.fina` because it's a connected ligature to its previous character, but that's a never-connecting alef.

**Comment by Tarobish** [comment]
True :) sorry my bad. i told you, you are an export in Arabic right now :))))

**Comment by graphicore** [comment]
:-) No problem, it was no complaint, I was just dropping a note so that there's ~~no~~ less confusion when someone from the future tries to follow what happened here.

**Comment by Tarobish** [comment]
I know :)

**Comment by graphicore** [comment]
From the second block, some of the ligatures are already in the first block:

dotlessbeh_alefMaksura-ar = uni066E0649
dotlessbeh_noonghunna-ar = uni066E06BA
dotlessbeh_reh-ar = uni066E0631
dotlessfeh_alefMaksura-ar = uni06A10649

**Comment by graphicore** [comment]
[Issue #85.01: colliding bottom marks](http://tarobish.github.io/Mirza/html/generated-pages.html#testsKern/Issue%20%2385.01%3A%20colliding%20bottom%20marks)
[Issue #85.01-B: colliding bottom marks](http://tarobish.github.io/Mirza/html/generated-pages.html#testsKern/Issue%20%2385.01-B%3A%20colliding%20bottom%20marks)
[Issue #85.02: colliding bottom marks](http://tarobish.github.io/Mirza/html/generated-pages.html#testsKern/Issue%20%2385.02%3A%20colliding%20bottom%20marks)
[Issue #85.02-B: colliding bottom marks](http://tarobish.github.io/Mirza/html/generated-pages.html#testsKern/Issue%20%2385.02-B%3A%20colliding%20bottom%20marks)
[Issue #85.03: colliding bottom marks](http://tarobish.github.io/Mirza/html/generated-pages.html#testsKern/Issue%20%2385.03%3A%20colliding%20bottom%20marks)

#85.03 is probably the most interesting. Maybe we can do it as in Katibeh: you mark the important cases for me.

**Comment by Tarobish** [comment]
Ready

![screen shot 2016-02-11 at 8 08 17 pm](https://cloud.githubusercontent.com/assets/8403973/12998857/53b6482a-d0fd-11e5-98b8-6f7a7dec4509.png)
![screen shot 2016-02-11 at 8 07 49 pm](https://cloud.githubusercontent.com/assets/8403973/12998861/53c5bb8e-d0fd-11e5-8531-ae21ca36216b.png)
![screen shot 2016-02-11 at 7 55 33 pm](https://cloud.githubusercontent.com/assets/8403973/12998858/53bde1e8-d0fd-11e5-9fcf-b505a22df9df.png)
![screen shot 2016-02-11 at 8 07 25 pm](https://cloud.githubusercontent.com/assets/8403973/12998862/53cb49f0-d0fd-11e5-9bbe-c62e6ffc48e3.png)
![screen shot 2016-02-11 at 8 08 06 pm](https://cloud.githubusercontent.com/assets/8403973/12998859/53c43b9c-d0fd-11e5-9109-9126830f57aa.png)
![screen shot 2016-02-11 at 8 08 20 pm](https://cloud.githubusercontent.com/assets/8403973/12998860/53c45884-d0fd-11e5-9b6e-ac49deba10e1.png)
![screen shot 2016-02-11 at 7 55 15 pm](https://cloud.githubusercontent.com/assets/8403973/12998863/53ce9ede-d0fd-11e5-9adf-1832e1e249b6.png)
![screen shot 2016-02-11 at 8 07 36 pm](https://cloud.githubusercontent.com/assets/8403973/12998864/53d8166c-d0fd-11e5-9b11-fab431919342.png)
![screen shot 2016-02-11 at 8 07 54 pm](https://cloud.githubusercontent.com/assets/8403973/12998865/53df8280-d0fd-11e5-896f-e66ddce4f7a0.png)
![screen shot 2016-02-11 at 8 07 31 pm](https://cloud.githubusercontent.com/assets/8403973/12998866/53e1c7ac-d0fd-11e5-8927-89bc78c8ef5a.png)
![screen shot 2016-02-11 at 8 08 11 pm](https://cloud.githubusercontent.com/assets/8403973/12998867/53e44f68-d0fd-11e5-8ecb-120cca337166.png)
![screen shot 2016-02-11 at 8 03 17 pm](https://cloud.githubusercontent.com/assets/8403973/12998868/53e75640-d0fd-11e5-94e8-764a16f6f333.png)
![screen shot 2016-02-11 at 8 03 23 pm](https://cloud.githubusercontent.com/assets/8403973/12998869/53ea0fca-d0fd-11e5-9088-e02c2424fe17.png)

**Comment by graphicore** [comment]
What is wrong with this? Or what do you want me to do here?

![screen shot 2016-02-11 at 7 55 33 pm](https://cloud.githubusercontent.com/assets/8403973/12998858/53bde1e8-d0fd-11e5-9fcf-b505a22df9df.png)

I think I'll take this and the others that look OK as a "don't break it we need it".

Thus, I also do nothing with the last two images as well, unless you give me more specific actions for these.

**Comment by graphicore** [comment]
With the last two sheets that you provided. there are tiny collisions. Should we rather add a bit more space between the glyphs?

**Comment by graphicore** [comment]
OK, check the tables please.

**Comment by Tarobish** [comment]
It just need a bot more space

**Comment by Tarobish** [comment]
looks great!
