### ISSUE TITLE
Mirza—Generated Test Pages - issues

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#87]
issue#7-1 Ligatures are broken in some cases 

---

issue#11-2 (LamAlfFina)
Lighters are broken  in some cases 

---

Issue #5: Ligature 05 (uni066E06BA)
In the first row it has to be "Yeh with ring below" (yehKashmiri-ar.init & yehKashmiri-ar.medi) based on Amiri 
![screen shot 2016-01-22 at 4 27 08 pm](https://cloud.githubusercontent.com/assets/8403973/12526691/09a9e120-c125-11e5-8e3d-7db36b889761.png)

---

Issue #54: ligature 54 (uni064306440627)
In some cases ligatures are broken
![screen shot 2016-01-22 at 4 51 23 pm](https://cloud.githubusercontent.com/assets/8403973/12526943/74dcd968-c128-11e5-9299-5c85979bbb8e.png)

---

Issue #55: ligature 55 (uni064306440627.fina)
In some cases ligatures are broken

---

Issue #60: Colliding glyph combinations 01
Still we have colliding problem

---

Issue #61: colliding glyph combinations 02
Still we have colliding problem

---

Issue #62: colliding glyph combinations 03
Still we have colliding problem

---

Issue #63: colliding glyph combinations 04
Still we have colliding problem

---

Issue #64: colliding glyph combinations 05
Still we have colliding problem

---

Issue #65: colliding glyph combinations 06
Still we have colliding problem

**Comment by graphicore** [comment]
Looks all better to me now.
The #54 #55 cases where the ring is part of the base glyph could be healed with the dismissed proposal in #98
