### ISSUE TITLE
generate ufos

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#88]
Hi, @Tarobish 

I need you to do some things for me:
1.  Clean up the "Generated" directory. Delete everything but the `Documents` directory:
   - Mirza-Bold.ufo
   - Mirza-Regular.ufo
   - UFO -Kerning, With Production Names
   - UFO -Kerning, Without Production Names
   - UFO -Without Production Namas
   - Kerning.metrics
   - Mirza-Bold.ttf
   - Mirza-Medium.ttf
   - Mirza-Regular.ttf
   - Mirza-SemiBold.ttf
   
   (I would do it myself, but that will confuse SparkleShare, as it did in the past.)
2. Create a directory `Generated/Arabic` and `Generated/Latin`
3. In Glyphs Export the _instances_ of the fonts as `UFO` and as `OTF` into `Generated/Arabic`. Don't "save" the project, do "export" with the instances (I think it's at Cmd-E as a shortcut, judging from the [screenshot in here](https://glyphsapp.com/tutorials/testing-your-fonts-in-adobe-apps/)). If it asks you about production names chose "yes". Check "remove overlap" and check "autohint". Don't check "Save as TTF"
4. Do the same export for the Latin Glyphs-project from Eduardo. It's in `Sources/Mirza-LATIN-SOURCE.glyphs` (I just put it there maybe you have to refresh SparkleShare) into `Generated/Latin`

As a check, after exporting instances, there should be 4 UFOs and 4OTFs for each script.

Thank you very much!

**Comment by Tarobish** [comment]
Please check them and let me know, as well as "Katibeh"

**Comment by graphicore** [comment]
**About the ufos:** This are the exported masters. I was hoping you could export the _instances_ as ufo. If that's not possible at all, what you did is just fine.

Basically, what's missing are: `Mirza-SemiBold ... .ufo` and `Mirza-Medium ... .ufo`

**About the font files:** I need the `otf` files _not_ `ttf`.
This is because I'm going to use `makeoftf`of the AFDKO (Adobe Font Development Kit For Open Type) and that one needs `otf` as input. I can later convert the `otf`s myself to `ttf`.

**Comment by Tarobish** [comment]
Hi,
I just found a way and I did it
Generated the whole instance then exporting UFO and .metric separately 

Best,
- K

KB STUDIO

**Comment by graphicore** [comment]
Great! Yeah that looks good. Though, I don't need the `*.metrcis` files, that's what I'm going to use the ufos for.

Thanks!

**Comment by Tarobish** [comment]
Great :)

KB STUDIO
