### ISSUE TITLE
Center Dots position its broke in "tcheh-ar.fina" either on ligature or character position

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#89]

**Comment by graphicore** [comment]
as in Tarobish/Katibeh#82 [this is good now](http://tarobish.github.io/Mirza/html/live-testing.html#?eJxdkEEKwjAQRa9SIriykiZNGpOVqL2ArsRN0SiFWqUELIp3d2o7LczqvR/ebPJh10cdmGWvlHO2YMG3YVs28NCECra/78u3h5maZ4BdFfUNVtGAn+HS/4/ns5Zrk7oIhTKKTnXvEiPpKKdIY6Qd5RRlGGWOcozEZohAKDHKlOmjTijHSO+GCIRyinKMckeJkVmLPuqEEn71UoTuvwVPdMxFzFcHkVglrJJLmagj+/4AOUZoeQ==): 

![selection_063](https://cloud.githubusercontent.com/assets/393132/12932167/c1324278-cf81-11e5-934f-d44db4b16e60.png)

But be aware that as in Tarobish/Katibeh#82 some ligatures are missing center anchors. Please add them:

[uni066E062D](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2312%3A%20ligature%2012%20%28uni066E062D%29)

[uniFC40](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2359%3A%20ligature%2059%20%28uniFC40%29)

A bit offtopic but for uni0696.fina some other ligatures also need a center anchor:

[uni066E0631](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%234%3A%20Ligature%2004%20%28uni066E0631.fina%29)

[uni066E0631.fina](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%234%3A%20Ligature%2004%20%28uni066E0631.fina%29)

[uniFD0E](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2316%3A%20ligature%2016%20%28uniFD0E%29)

[uniFD2A](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2317%3A%20ligature%2017%20%28uniFD2A%29)

[uniFD0F](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2322%3A%20ligature%2022%20%28uniFD0F%29)

[uniFD2B](http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2323%3A%20ligature%2023%20%28uniFD2B%29)
