### ISSUE TITLE
Still we don't have style, i just changed the language to check the ligatures

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#90]

**Comment by graphicore** [comment]
This is a bit light on the description side.

**Comment by graphicore** [comment]
Is this the same as Tarobish/Katibeh#86?

**Comment by davelab6** [comment]
Yes it seems to be the same. @Tarobish please confirm.

**Comment by Tarobish** [comment]
"In the both case “Mirza” and “katibeh” special characters in the last build, works as a "Set 1 but ligatures still doesn't have any Style.

**Comment by graphicore** [comment]
Please can you confirm again that `ss01` works?

> ligatures still doesn't have any Style.

_There is no stylistic set for ligatures_. There is `rlig` and **`dilg`**.

`rlig`: Required Ligatures
`dilg`: Discretionary Ligatures

In Arabic all ligatures are on by default in the `rlig` feature.

In Urdu and Farsi only some ligatures are triggered via the `rlig` feature. Use `dlig` (default off) to turn on the rest of the ligatures that are present by default in Arabic. Does this work?

**Comment by Tarobish** [comment]
Yes :) s01 it works perfect
Sorry ignore my last comment
its works in farsi too, now we are good :)

**Comment by graphicore** [comment]
What about Farsi + `dlig` in InDesign? I know it works in Firefox.

**Comment by Tarobish** [comment]
It works in indesign too ;)
