### ISSUE TITLE
Colliding error

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#92]
![screen shot 2016-02-04 at 6 01 01 pm](https://cloud.githubusercontent.com/assets/8403973/12835965/52fd71fe-cb69-11e5-8f4f-cb0d1344301b.png)

**Comment by graphicore** [comment]
Indesign seems to screw up mark positioning when we it this way :-( Sadly I have no better idea how to do it. I can try one more thing, but It's probably not going to help either.

**Comment by graphicore** [comment]
Hmm, maybe when you add the `extender` glyph and give it top and bottom anchors it would use these?

**Comment by Tarobish** [comment]
Sorry i didn’t find it, would you please send me a link ?

**Comment by graphicore** [comment]
You can't find it, becuase you need to add it yourself.

https://github.com/Tarobish/Mirza/issues/60#issuecomment-180186544:

> By the way, the glyph used as extender is called extender. When you add it to the fonts, tell me, then I remove my version.

You said you would do so:

> the Connection it has to be very small, please add a new Keshida like "uni0640" as a connection part; later, i'll adjust the length

That connection glyph, when you add it call it `extender`

**Comment by graphicore** [comment]
I see you add the extender, did you also add the `top` and `bottom` anchors?
If yes, test it again please. If no, add the anchors and notify me, then I can update the fonts and you can test.

**Comment by Tarobish** [comment]
Done! i did it
please check it out :)

**Comment by graphicore** [comment]
Did you update the `*.otf` files in Generated?

**Comment by graphicore** [comment]
Ok, try it!
