### ISSUE TITLE
Dot's position its broken in "jeem-ar.medi" either in ligature or character positioning 

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#93]
![screen shot 2016-02-04 at 6 01 58 pm](https://cloud.githubusercontent.com/assets/8403973/12835974/708cebf0-cb69-11e5-885b-b6e59a236f19.png)

**Comment by graphicore** [comment]
Should be good now.

**Comment by graphicore** [comment]
see also #89
