### ISSUE TITLE
Broken Characters in Urdu & Uyghur

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#94]
The last page of "persian-arabic2_Mirza-SemiBold_8”
![screen shot 2016-02-04 at 6 04 24 pm](https://cloud.githubusercontent.com/assets/8403973/12836029/fed64596-cb69-11e5-872e-8afdcb173caf.png)

**Comment by Tarobish** [comment]
Close?

**Comment by graphicore** [comment]
Yeah, I did the same as in Tarobish/Katibeh#79
