### ISSUE TITLE
Latin - Arabic weight harmonization

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#95]
i think our latin compare to the Arabic one it has more thickness
in the sample we had, it wasn't like this :(
![screen shot 2016-02-04 at 7 34 29 pm](https://cloud.githubusercontent.com/assets/8403973/12837343/afb1a016-cb76-11e5-8600-752160246669.png)

**Comment by graphicore** [comment]
cc @davelab6 Is Edu on github?

**Comment by Tarobish** [comment]
ok :)

**Comment by etunni** [comment]
This comment is for all weights?

**Comment by Tarobish** [comment]
Yes, for all of them

Thanks!

**Comment by etunni** [comment]
We can change the weights on each instance.
Today values: Regular 400, Medium 500, Semibold 600, Bold 700
We can try substracting 50 units per weight like Regular to 350 in glyphs instance window.
Cheers, Edu
![screen shot 2016-02-11 at 15 27 28](https://cloud.githubusercontent.com/assets/5973399/12986035/086b1efa-d0d4-11e5-8dcc-76c934f61859.png)

**Comment by Tarobish** [comment]
ill try it and will let you know @etunni

**Comment by Tarobish** [comment]
much better, do you think that i can substracting 50 units more? @etunni

**Comment by etunni** [comment]
Hi,

First, try to subtract 25 units more.

Cheers
et

**Comment by graphicore** [comment]
Is this extrapolated? It can make errors the more you do of it. If so, be careful, and check the results. You can also make a very extreme extrapolation to see where the errors occur first/strongest, then check these positions in your moderately extrapolated fonts.

**Comment by Tarobish** [comment]
It was helpful. so lets not do this any more :) ill close it

**Comment by graphicore** [comment]
Are you happy with it?

**Comment by graphicore** [comment]
If so, please update the Lating Glyphs file and the Generated/Latin directory.

**Comment by Tarobish** [comment]
sure :)

**Comment by Tarobish** [comment]
its all there
