### ISSUE TITLE
Glyphs with "stuff" merged into the base form don't decompose.

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Mirza#98]
This is a common problem that we have in Mirza, as well as in Katibeh. There are certain glyphs with for example a ring (or horizontal strokes etc.) merged into their base form. These glyphs can't be decomposed into a base form plus marks. Hence most of our features don't work for these glyphs.

My preferred solution would be to make custom marks glyphs out of these additions. Then add a custom anchor to the base forms and the marks, plus to the ligatures that are created from these bases. That way we could use the existing features to form ligatures out of these special glyphs.

Alternativeley, if this is not possible, we'd need to make custom ligatures for these special characters. If we want to have ligatures of them.
### suggestion

Let's take the case of `uni06B0` (ARABIC LETTER GAF WITH RING):
The ring is `uniFBBF`(ARABIC SYMBOL RING)
and the base is `06A9`(ARABIC LETTER KEHEH) + the gafbarar mark (GAF is 06AF)
and the bases of the `init`, `medi`,`fina` forms are in order `uniFB90`, `uniFB91`, `uniFB8F`

We should make a new ring mark like `uniFBBF.bodyattached` or `ring-ar.bodyattached` and give it a new custom mark anchor: `_custom` or `_bodyattachment`

Then we should give all bases AND the ligatures the `bodyattachment` base annchor.

I could then decompose `uni06B0` in e.g. the `feature medi` into `uniFB91 + gafbar-ar + ring-ar.bodyattached`and the ligatures would kick in.

Here are some randomly picked examples, not complete probably:

http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2335%3A%20ligature%2035%20%28uniFC3D%29

![selection_039](https://cloud.githubusercontent.com/assets/393132/12858498/cb596d46-cc50-11e5-99f7-ec3fb8ba5754.png)

http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%235%3A%20Ligature%2005%20%28uni066E06BA%29

![selection_040](https://cloud.githubusercontent.com/assets/393132/12858561/1cd08650-cc51-11e5-9c89-49691c32a46f.png)

http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2346%3A%20ligature%2046%20%28uniFC42%29

![selection_041](https://cloud.githubusercontent.com/assets/393132/12858589/487ee49a-cc51-11e5-84b1-7bf0d9b19338.png)

http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2351%3A%20ligature%2051%20%28uniFC81%29 (not how it happens twice in the third row)

![selection_042](https://cloud.githubusercontent.com/assets/393132/12858609/79d1e542-cc51-11e5-9995-af12105ee341.png)

**Comment by graphicore** [comment]
@Tarobish: If we don't do this we are much faster, but we have these places where ligatures don't appear etc. It's your decision, I can't really judge the linguistic implications.

**Comment by Tarobish** [comment]
Exactly, thats what i was thinking :D i checked "Amiri" as well. its better to leave them as they are
