### ISSUE TITLE
Extension part

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Mirza#99]
It works perfect just I'm not sure it happens because of indesign or its error
the extension part has been applied when"Alef" docent have a marks below. it shouldn't be here :)
![screen shot 2016-02-06 at 10 05 31 am](https://cloud.githubusercontent.com/assets/8403973/12868396/b4097b08-ccba-11e5-8a74-5bfc6f16d6fd.png)
![screen shot 2016-02-06 at 10 05 50 am](https://cloud.githubusercontent.com/assets/8403973/12868404/ec919f6e-ccba-11e5-8cca-a4abbd0aae68.png)

**Comment by graphicore** [comment]
Should be good now
